### ISSUE TITLE
Doesn't compile in elixir 1.15.4 or 1.15.5

### ISSUE THREAD

**Issue by AdamSak** [TheFirstAvenger/elixir-simple_agent#1]
Simple issue just missing `()` on line 11-13

error: undefined variable "deps"
  /Users/adamsak/Sites/verb/project/deps/simple_agent/mix.exs:11: SimpleAgent.Mixfile.project/0

error: undefined variable "description"
  /Users/adamsak/Sites/verb/project/deps/simple_agent/mix.exs:12: SimpleAgent.Mixfile.project/0

error: undefined variable "package"
  /Users/adamsak/Sites/verb/project/deps/simple_agent/mix.exs:13: SimpleAgent.Mixfile.project/0

warning: function deps/0 is unused
  /Users/adamsak/Sites/verb/project/deps/simple_agent/mix.exs:38: SimpleAgent.Mixfile (module)

warning: function description/0 is unused
  /Users/adamsak/Sites/verb/project/deps/simple_agent/mix.exs:42: SimpleAgent.Mixfile (module)

warning: function package/0 is unused
  /Users/adamsak/Sites/verb/project/deps/simple_agent/mix.exs:46: SimpleAgent.Mixfile (module)

**Comment by TheFirstAvenger** [comment]
This is fixed in [v0.0.8](https://hex.pm/packages/simple_agent/0.0.8)
